import type { Metadata, Viewport } from 'next';
import { Nunito } from 'next/font/google';
import Image from 'next/image';
import './globals.css';

const nunito = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Bulletin Board',
  description: 'Generated by dihoon',
  formatDetection: {
    email: false,
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-svh overflow-hidden overscroll-x-none">
      <body
        className={`${nunito.className} relative flex h-full flex-col overflow-y-auto`}
      >
        <Image
          className="!fixed top-0 -z-10 !object-cover brightness-50 filter"
          src="/images/tree.jpg"
          alt="배경화면"
          fill
        />
        <div className="flex flex-1 flex-col">{children}</div>
      </body>
    </html>
  );
}
